export const RARIBLE_FETCH_REQUEST = 'RARIBLE_FETCH_REQUEST';
export const RARIBLE_FETCH_SUCCESS = 'RARIBLE_FETCH_SUCCESS';
export const RARIBLE_FETCH_FAILED = 'RARIBLE_FETCH_FAILED';

export const OPENSEA_FETCH_REQUEST = 'OPENSEA_FETCH_REQUEST';
export const OPENSEA_FETCH_SUCCESS = 'OPENSEA_FETCH_SUCCESS';
export const OPENSEA_FETCH_FAILED = 'OPENSEA_FETCH_FAILED';

export const CONNECT_RELAY_NODE = 'CONNECT_RELAY_NODE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SET_VALUES = 'SET_VALUES';
export const SET_WALLET = 'SET_WALLET';
